-- AI disclosure on articles (Google AdSense / Google Search policy compliance).
--
-- Context: Google's Quality Guidelines updated in 2024-2025 now flag
-- "scaled content abuse" — mass-generated AI content without disclosure.
-- Articles generated by the /api/articles/generate endpoint (Anthropic
-- multi-agent pipeline) must be marked explicitly so :
--   1. The front-end can show an "Article généré avec assistance IA" badge
--   2. Google's crawlers receive honest metadata (meta tag + schema.org)
--   3. The site demonstrates E-E-A-T good faith
--
-- The existing legacy imports from Zone Nordiques (batch of 30 March 2026)
-- are ALSO marked is_ai_generated = TRUE because the original content was
-- processed through the AI agents when imported. Keeping the flag honest
-- is what matters for AdSense compliance.

ALTER TABLE public.articles
  ADD COLUMN IF NOT EXISTS is_ai_generated BOOLEAN DEFAULT FALSE NOT NULL;

-- Backfill: mark every article already in the table as AI-generated, since
-- the entire corpus was imported via the AI pipeline on 2026-03-30.
-- New human-written articles created after this migration will default to FALSE
-- unless the editor explicitly flags them.
UPDATE public.articles
SET is_ai_generated = TRUE
WHERE is_ai_generated IS DISTINCT FROM TRUE;

COMMENT ON COLUMN public.articles.is_ai_generated IS
  'Whether this article was generated with AI assistance. Used to render the '
  'AI disclosure badge on the public article page and to inform schema.org '
  'metadata (E-E-A-T compliance with Google''s scaled-content policy).';

CREATE INDEX IF NOT EXISTS idx_articles_is_ai_generated
  ON public.articles(is_ai_generated)
  WHERE is_ai_generated = TRUE;
